### DISCUSSION TITLE
Local debugging

### DISCUSSION THREAD

**Discussion by InsideTheo** [TouK/nussknacker#3544] [Q&A] [answered]
Hello,

I would like to debug the code (especially the parts that deploy a job to Flink and the parts that interprete the Model Json) locally. However it is hard for me to get all the dependencies to run. Also the config that is specified in NussknackerApp.run.xml seems outdated, since its very different to what the quickstart project deploys (for example the Flink Urls dont match). Is there an easy way to get all dependencies to run locally and connect them to local designer?

Kind regards

**Comment by arkadius** [comment, marked as answer]
> Also the config that is specified in NussknackerApp.run.xml seems outdated, since its very different to what the quickstart project deploys (for example the Flink Urls dont match)

What exactly do you mean by that? I see:
```
<env name="FLINK_REST_URL" value="http://localhost:3031" />
```
in NussknackerApp.run.xml

and:
```
  jobmanager:
    container_name: nussknacker_jobmanager
    image: apache/flink:${FLINK_VERSION-1.15.2}-scala_${SCALA_VERSION-2.12}-${JAVA_VERSION-java11}
    ports:
      - "3031:8081"
      - "9249:9249"
```
in quickstart.

Looks like ports matches.

> Is there an easy way to get all dependencies to run locally and connect them to local designer?

Yes it is described in [CONTRIBUTING.md](https://github.com/TouK/nussknacker/blob/staging/CONTRIBUTING.md#running-using-integration-environment)

However we don't use this method too often during development. For debugging Flink execution it is more easier to write test that will be run on embedded Flink. It is described in [developers guide](https://nussknacker.io/documentation/docs/next/developers_guide/Testing/)
